# This is a basic workflow to help you get started with Actions

name: armTempateDeployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  ArmDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.4.6
          with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

          - name: Deploy Resource Group rg-githubactions with AZ CLI
            uses: Azure/cli@v1.0.8
            with:
              inlinescript: |
                az deployment sub create --location "eastus" --template-file ./arm-templates/resouregroup.json
      
  
