# This is a basic workflow to help you get started with Actions

name: armTempateDeployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  ArmDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy resource group rg-githubactions
        uses: Azure/arm-deploy@v1.0.9
        with:
          scope: subscription
          subscriptionId: e693c25d-601a-4c2c-b613-2c26a18f489b
          region: Eastus
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubactions
      
      
  
