# This is a basic workflow to help you get started with Actions

name: armTempateDeployment

on:

  workflow_dispatch:

jobs:
  ArmDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      -name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.Azure_credentials }}

  
