# This is a basic workflow to help you get started with Actions

name: armTempateDeployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  resource_group_name: rg-githubactions
  location: "east us"
  subscriptionId: e693c25d-601a-4c2c-b613-2c26a18f489b
jobs:
  ArmDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy resource group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1.0.9
        with:
          scope: subscription
          subscriptionId: ${{ env.subscriptionId }}
          region: Eastus
          template: ./arm-templates/resourcegroup.json
          parameters:
            location= ${{ env.location }}
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}
      
      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1.0.9
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm-templates/storageaccount.json
          parameters: 
            sku=Standard_LRS
            storageAccountName=globostg003drt 
            location=${{ env.location }}
          deploymentMode: incremental

      - name: Deploy Virtual Machine
        uses: Azure/arm-deploy@v1.0.9
        with:
            scope: resourcegroup
            resourceGroupName: ${{ env.resource_group_name }}
            subscriptionId: ${{ env.subscriptionId }}
            template: ./arm-templates/virtualmachine.json
            parameters: 
              adminPassword=${{ secrets.UBUNTU_ADMIN_PASSWORD }}
              location=${{ env.location }}
            deploymentMode: incremental

      
  
